name: Build and test

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Prepare
        run: |
          cd src
          npm install --silent
          npm run build
          npm run test
          cd dist
          npm link
          cd ..
          cd ..
          npm install -g @angular/cli@next
          ng new your-angular-project --defaults
          cd your-angular-project
          npm link @angular-schule/ngx-deploy-starter
          ng add @angular-schule/ngx-deploy-starter

      - name: Deploy
        run: |
          mkdir $GITHUB_WORKSPACE/example-folder
          cd your-angular-project
          ng deploy --target-dir=$GITHUB_WORKSPACE/example-folder
